### ISSUE TITLE
Allow declarative datasets authorization 

### ISSUE THREAD

**Issue by wtrocki** [feedhenry/fh-sync-server#21]
Allow declarative authorization mechanisms that will prevent users from creating filters and getting access to the restricted data.

For example:
```
{
  "rules": {
    "users": {
      "$uid": {
        ".write": "$uid === auth.uid"
      }
    }
  }
}
```
Very good example of this idea implemented in firebase:
https://firebase.google.com/docs/database/security/

**Comment by wtrocki** [comment]
FYI @wei-lee @david-martin - Idea presented on sync brainstorm session. 
I'm not sure if this should be sync or sync server issue.

**Comment by maleck13** [comment]
Thanks for creating the issue, @wtrocki, there is something similar to this in the sync backlog https://trello.com/c/gBWQphnv/111-as-a-developer-i-want-client-side-permission-checks-on-token-validity-and-roles-permissions-checks-so-that-i-can-fail-fast-on-th

**Comment by wtrocki** [comment]
@maleck13 - Great that you have it mapped in trello. I'm going to close this ticket.
